### ISSUE TITLE
Required `json` property not found

### ISSUE THREAD

**Issue by isacaraujo** [mulesoft-labs/api-console-builder#10]
This **BUG** was fetched from this other: [mulesoft-labs/api-console-cli #18](https://github.com/mulesoft-labs/api-console-cli/issues/18).

This package was broken after an update of raml2html/raml2obj.

We need to fix this package before fix the `api-console-cli`.

**Comment by torsjonas** [comment]
I can add that the mocha tests all succeed when I run them locally but seeing lots of logs:
`TypeError: datatype_expansion.canonical_form.Exception is not a constructor`
which points to an issue with the `raml2obj` module.

**Comment by jarrodek** [comment]
Fixed by https://github.com/mulesoft-labs/api-console-builder/commit/977e23ee6c960eb15bac7b5b633091c0bbfc0865
